### PR TITLE
fix: Cloud deployments to respect existing renv.lock file

### LINKED ISSUE #3356: Deployment fails with renv.lock due to missing shiny package
## Problem statement

Publisher fails to deploy a Shiny application when a valid project-level `renv.lock` is present. During deployment, Publisher generates or uses a different `renv.lock` under `.posit/publish/deployments/`, which omits required packages (including `shiny`). This results in an incomplete R environment and a startup failure, despite `renv.lock` existing at the repository root and a manifest file being generated as documented.

## Steps to reproduce

Using publisher, I went through the process of deploying the app.

I also followed instructions [here](https://rstudio.github.io/renv/articles/rsconnect.html) to generate a manifest file to use.

**Expected behavior:** App deployment.

Publisher should:
- Respect the project-level `renv.lock`, or
- Use the provided manifest consistently, and
- Install all required packages listed there, including `shiny`.

**Actual behavior:** Did not deploy.

- Publisher generates or uses a different `renv.lock` at `.posit/publish/deployments/renv.lock`.
- This generated lockfile does **not** match the project-level `renv.lock`.
- The resulting environment omits required packages.

## Publishing information

```text
Positron Version: 2025.09.0 build 139
Code - OSS Version: 1.103.0
Commit: 30e3d0a74e09a0f6640929822cb57a326671360e
Date: 2025-08-29T18:31:52.943Z (3 mos ago)
Electron: 37.2.3
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Darwin x64 24.6.0
```

Account: uab-cgds-team

## Publisher output and logs

```text
2025-12-15T14:01:07-06:00 Your publish request with ID a6791966-e121-4a65-8705-cf276e7d97f1 is now being processed.
2025-12-15T14:01:07-06:00 Loading your source code...
2025-12-15T14:01:07-06:00 Installing your code's dependencies into the environment.
2025-12-15T14:01:08-06:00 Collecting your code's R dependencies...
2025-12-15T14:01:08-06:00 Connect Cloud is providing all 16 required R packages:
2025-12-15T14:01:08-06:00 boot@1.3-32, class@7.3-23, cluster@2.1.8.1, codetools@0.2-20, foreign@0.8-90
2025-12-15T14:01:08-06:00 KernSmooth@2.23-26, lattice@0.22-7, MASS@7.3-65, Matrix@1.7-4, mgcv@1.9-4
2025-12-15T14:01:08-06:00 nlme@3.1-168, nnet@7.3-20, renv@1.1.5, rpart@4.1.24, spatial@7.3-18
2025-12-15T14:01:08-06:00 survival@3.8-3
2025-12-15T14:01:08-06:00 Using Quarto version: 1.8.24
2025-12-15T14:01:08-06:00 Running on host: deployment-019b239a-436492ad0f1f2e857f5b0a2441ba2eb7-deplox9lkc
2025-12-15T14:01:08-06:00 Process ID: 105
2025-12-15T14:01:08-06:00 Running as user: uid=10002(connect) gid=10002(connect) groups=10002(connect)
2025-12-15T14:01:08-06:00 Connect version: 2025.11.0
2025-12-15T14:01:08-06:00 LANG: C.UTF-8
2025-12-15T14:01:08-06:00 Working directory: /cloud/project
2025-12-15T14:01:08-06:00 Using R 4.5.1
2025-12-15T14:01:08-06:00 R.home(): /opt/R/4.5.1/lib/R
2025-12-15T14:01:08-06:00 Content will use current R environment
2025-12-15T14:01:08-06:00 R_LIBS: (unset)
2025-12-15T14:01:08-06:00 .libPaths(): /cloud/lib/x86_64-pc-linux-gnu-library/4.5, /opt/R/4.5.1/lib/R/library
2025-12-15T14:01:08-06:00 shiny version: (none)
2025-12-15T14:01:08-06:00 httpuv version: (none)
2025-12-15T14:01:08-06:00 rmarkdown version: (none)
2025-12-15T14:01:08-06:00 knitr version: (none)
2025-12-15T14:01:08-06:00 jsonlite version: (none)
2025-12-15T14:01:08-06:00 RJSONIO version: (none)
2025-12-15T14:01:08-06:00 htmltools version: (none)
2025-12-15T14:01:08-06:00 reticulate version: (none)
2025-12-15T14:01:08-06:00 Error in enforcePackage(name, curVersion) : 
2025-12-15T14:01:08-06:00   The shiny package was not found in the library.
2025-12-15T14:01:08-06:00 Calls: local ... eval -> eval -> eval -> <Anonymous> -> enforcePackage
2025-12-15T14:01:08-06:00 Execution halted
2025-12-15T14:01:08-06:00 Failed to publish content: Your application failed to start. error_id=9fc6bc24-a509-463b-9560-4134e23792ef
```

### PR DESCRIPTION
**Pull request by marcosnav**
## Intent

Posit Cloud deployments have differences in config schema which override the `R.PackageFile` default value. When a customer already has an existing `renv.lock` it is ignored and Publisher generates and uses a new one at `.posit/deployments/renv.lock`

This PR introduces a `GetPackageFile` method to the `Config.R` entity so the value is consistent and properly handled regardless of publishing to Connect or Posit Cloud.

Fixes #3356 

## Type of Change

- - [x] Bug Fix 
- - [ ] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## User Impact

Existing user's `renv.lock` file should be respected and used to generate the manifest when publishing to Posit Cloud.

## Automated Tests

Updated the related unit tests.

## Directions for Reviewers

The following scenarios should work for both Connect and Posit Cloud:
- [ ] Deploying a project with an existing `renv.lock` file. The generated manifest should use the existing lockfile, no `renv.lock` should be created under `.posit/deployments/...`
- [ ] Deploying a project with NO existing `renv.lock` file. An automatically generated `renv.lock` should exist under `.posit/deployments/...`, manifest should use R package descriptions from it.

## Checklist

- [ ] I have updated the _root_ [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

File: internal/publish/manifest.go [hunk 1]
```diff
@@ -20,14 +20,14 @@ func (p *defaultPublisher) createManifest() (*bundles.Manifest, error) {
...
 		// use the interpreter's discovery (which falls back to renv.lock).
-		if p.Config.R.PackageFile != "" {
-			lockExists, err := p.Dir.Join(p.Config.R.PackageFile).Exists()
-			scanDependencies = (err != nil) || !lockExists
-			if err != nil {
-				p.log.Debug("Error checking existence of configured R lockfile", "lockfile", p.Config.R.PackageFile, "error", err)
-			}
-		} else {
-			scanDependencies = true
+		lockExists, err := p.Dir.Join(p.Config.R.GetPackageFile()).Exists()
```
Comment (dotNomad) [inline internal/publish/manifest.go]: Should this care if the package file is selected as included in the configuration?

If I have a local `renv.lock`, but I don't have selected I think I would expect to see behavior described below:

> Deploying a project with NO existing renv.lock file. An automatically generated renv.lock should exist under .posit/deployments/..., manifest should use R package descriptions from it.

**Review by mslynch — APPROVED** [review]
