### PR TITLE
Fixing multiple bugs for Connect Cloud support

### LINKED ISSUE #2680: Support opening the deployment logs from the Homeview
### Description

Add a link for the Connect Cloud deployment logs in the Homeview.

### LINKED ISSUE #2775: improve messaging for Connect Cloud creation
When the extension kicks you over to the UI to create a Connect Cloud account, and the prompt is asking if you want to open the external website (the `/account/done` page), it would be helpful to include a message in the multistepper like "Waiting for account creation..." instead of "Retrieving accounts from Connect Cloud". Otherwise first-time users won't actually know why it's opening a new page.

Note this will only apply to VS Code users since Positron trusts our domain already.

Image

### LINKED ISSUE #2842: Creating a new credential for Connect Cloud overrides the existing credential for the deployment in the extension
Add details w/ screenshot

### LINKED ISSUE #2843: Publishing a Connect Cloud deployment reports the wrong account link
After creating a new credential and having it wrongfully override the existing credential for the deployment, if you click to publish, the publishing will happen correctly but using the latest created credential and the deployment and logs will link to page not found if the account display name is different from the account name.

https://github.com/user-attachments/assets/7cb739ec-c83d-4d47-86fc-7501e3c8e8d1

### LINKED ISSUE #2844: The logs link is using the account display name rather than the account name for Connect Cloud deployments
This results in a broken link.

### PR DESCRIPTION
**Pull request by rodriin**
## Intent

Resolves #2842
Resolves #2843
Resolves #2844
Resolves #2680
Resolves #2775

The intent of this PR is to fix a few known bugs for Connect Cloud support ahead of the bug bash.

## Type of Change

- - [x] Bug Fix 
- - [ ] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## Approach

A lot of the fixes are about making the messaging Connect Cloud friendly by conditionally displaying something different when the associated product is Connect Cloud or just simple rewording. There are other fixes that were a little more involved like using the account name vs the account display name when saving credential data so links would be correct. This also enabled the credential look-up for deployments to be correct because we could use the account name.

## User Impact

None because Connect Cloud support has not been released yet.

## Automated Tests

Existing E2E tests succeeded locally for this branch.

## Directions for Reviewers

Verify that all bugs associated to this PR have been fixed.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

File: extensions/vscode/src/api/types/contentRecords.ts [hunk 1]
```diff
@@ -63,6 +67,7 @@ type ContentRecordRecord = {
   configurationName: string;
   type: ContentType;
   deploymentError: AgentError | null;
+  connectCloud: ConnectCloud | null;
```
Comment (rodriin) [inline extensions/vscode/src/api/types/contentRecords.ts:70]: Surfacing the Connect Cloud account name within the `ContentRecordRecord` object so we can correctly match a Connect Cloud configuration to a credential.

File: extensions/vscode/src/multiStepInputs/common.ts [hunk 2]
```diff
@@ -156,20 +156,19 @@ export const inputCredentialNameStep = async (
...
   const resp = await input.showInputBox({
     title: state.title,
     step: 0,
     totalSteps: 0,
-    value: currentName || preFilledName,
+    // default the credential name to the account display name for Connect Cloud when available
+    value: currentName || accountDisplayName,
     prompt: `Enter a unique nickname for this ${isConnectCloud(serverType) ? "account" : "server"}.`,
-    placeholder: `${isConnectCloud(serverType) ? accountName : productName}`,
+    placeholder: `${isConnectCloud(serverType) ? accountDisplayName : productName}`,
```
Comment (rodriin) [inline extensions/vscode/src/multiStepInputs/common.ts:171]: Minor refactor for the pre-filled account name to use display name correctly when creating a new credential for Connect Cloud. `displayName` is only expected to be present for Connect Cloud credentials.

File: extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts [hunk 3]
```diff
@@ -137,6 +137,7 @@ export async function newConnectCloudCredential(
         refreshToken: <string | undefined>undefined, // eventual type is string
         accountId: <string | undefined>undefined, // eventual type is string
         accountName: <string | undefined>undefined, // eventual type is string
+        displayName: <string | undefined>undefined, // eventual type is string
```
Comment (rodriin) [inline extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts:140]: Adding display name to the state to keep track of the account display name separately from the account name, which is the slug. The account name is part of the account data that gets associated and saved when a credential is created, the display name is used as the default credential name.

File: extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts [hunk 4]
```diff
@@ -293,6 +294,12 @@ export async function newConnectCloudCredential(
   ) {
     const accessToken =
       typeof state.data.accessToken === "string" ? state.data.accessToken : "";
+    const value = connectCloudData.shouldPoll
+      ? "Waiting for account setup in Connect Cloud..."
+      : "Retrieving accounts from Connect Cloud ...";
+    const message = connectCloudData.shouldPoll
+      ? "Please complete your account setup or 'Escape' to abort"
+      : "Please wait while we get your account data or 'Escape' to abort";
```
Comment (rodriin) [inline extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts:302]: It is safe to assume that whenever the `shouldPoll` property is `true` it means we are polling the accounts endpoint in `vivid-api` to get the accounts for the user because they are going through the account setup process. Therefore, we want to display a slightly different messaging to the user as they complete the account set up in Connect Cloud.

File: extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts [hunk 5]
```diff
@@ -423,7 +430,8 @@ export async function newConnectCloudCredential(
     const account = accounts.find((a) => a.displayName === pick.label);
     // fallback to the first publishable account if the selected account is ever not found
     state.data.accountId = account?.id || accounts[0].id;
-    state.data.accountName = account?.displayName || accounts[0].displayName;
+    state.data.accountName = account?.name || accounts[0].name;
+    state.data.displayName = account?.displayName || accounts[0].displayName;
```
Comment (rodriin) [inline extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts:434]: This is the fix for the bug where the account display name was being saved in the credential rather than the account name (slug). Therefore the user could possibly get a broken link with spaces because the display name allows spaces when it needed to be using the slug instead to make the content deployment link and logs link. This fixes that issue.

File: extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts [hunk 6]
```diff
@@ -371,7 +377,8 @@ export async function newConnectCloudCredential(
         steps[step.INPUT_CRED_NAME](input, state);
       // populate the selected account props
       state.data.accountId = accounts[0].id;
-      state.data.accountName = accounts[0].displayName;
+      state.data.accountName = accounts[0].name;
+      state.data.displayName = accounts[0].displayName;
```
Comment (rodriin) [inline extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts:381]: One more place where the credential account info saved needed to be fixed (account display name => account name).

File: extensions/vscode/src/views/homeView.ts [hunk 7]
```diff
@@ -1234,7 +1241,15 @@ export class HomeViewProvider implements WebviewViewProvider, Disposable {
...
-          details.push(`Missing Credential for ${contentRecord.serverUrl}`);
+          const serverType = contentRecord.serverType || ServerType.CONNECT;
+          const productType = getProductType(serverType);
+          let message = "Missing Credential";
+          if (isConnectCloudProduct(productType)) {
+            message += ` for ${ProductName.CONNECT_CLOUD}`;
+          } else if (isConnectProduct(productType)) {
+            message += ` for ${contentRecord.serverUrl}`;
+          }
+          details.push(message);
```
Comment (rodriin) [inline extensions/vscode/src/views/homeView.ts:1252]: Making the messaging Connect Cloud friendly.

File: extensions/vscode/src/views/homeView.ts [hunk 8]
```diff
@@ -1830,6 +1845,22 @@ export class HomeViewProvider implements WebviewViewProvider, Disposable {
...
+    if (isConnectProduct(productType)) {
+      this.context.subscriptions.push(
+        commands.registerCommand(
+          Commands.HomeView.AssociateDeployment,
+          () => showAssociateGUID(this.state),
+          this,
+        ),
+      );
+    }
+
```
Comment (rodriin) [inline extensions/vscode/src/views/homeView.ts:1863]: Conditionally adding a this command for Connect only, but I need help to conditionally exclude the option from the dropdown menu here:

https://github.com/posit-dev/publisher/blob/6cbe121145c1913cf6888ffe662e83ce240f9cd0/extensions/vscode/package.json#L357-L360

This code is very difficult to follow and I could not figure out how to conditionally remove the dropdown option. Help will be greatly appreciated and I do plan on addressing this on a separate PR.

File: extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue [hunk 9]
```diff
@@ -113,7 +113,7 @@
         v-if="home.config.active.isCredentialMissing"
         data-automation="missing-creds"
       >
-        A Credential for the Deployment's server URL was not found.
+        No credential was found for the deployment's server.
```
Comment (rodriin) [inline extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue:116]: Making the messaging Connect Cloud friendly.

File: extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue [hunk 10]
```diff
@@ -382,7 +389,15 @@ const credentialSubTitle = computed(() => {
...
-  return `Missing Credential for ${home.selectedContentRecord?.serverUrl}`;
+  const serverType =
+    home.selectedContentRecord?.serverType || ServerType.CONNECT;
+  const productType = getProductType(serverType);
+  if (isConnectCloudProduct(productType)) {
+    return `Missing Credential for ${ProductName.CONNECT_CLOUD}`;
+  } else if (isConnectProduct(productType)) {
+    return `Missing Credential for ${home.selectedContentRecord?.serverUrl}`;
+  }
+  return "Missing Credential";
```
Comment (rodriin) [inline extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue:400]: Making the messaging Connect Cloud friendly.

File: extensions/vscode/webviews/homeView/src/stores/home.ts [hunk 11]
```diff
@@ -123,12 +129,28 @@ export const useHomeStore = defineStore("home", () => {
...
+        const credentialUrl = cfg.url.toLowerCase();
+        const recordUrl = selectedContentRecord.value?.serverUrl.toLowerCase();
+        if (!recordUrl) {
+          return false;
+        }
+        return normalizeURL(credentialUrl) === normalizeURL(recordUrl);
       }
-      return normalizeURL(credentialUrl) === normalizeURL(recordUrl);
+
+      return false;
```
Comment (rodriin) [inline extensions/vscode/webviews/homeView/src/stores/home.ts:153]: Making the messaging Connect Cloud friendly.
