### PR TITLE
fix(runtime): Fix inconsistent runtime discovery and selection when deploying from Positron

### LINKED ISSUE #2648: Not detecting the R interpreter that is active in positron
## System details

    Publisher Version        : 1.14.0
    Connect Version          : dev
    Your OS                  : macOS 15.4.1
    Content Type to Deploy   : shiny app

## Publisher Output and Logs

<details>

```
time=2025-05-16T07:32:51.529-05:00 level=DEBUG msg="Picking directory from request" directory=.
time=2025-05-16T07:32:51.530-05:00 level=DEBUG msg="Validating path to R executable found" path=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R
time=2025-05-16T07:32:51.530-05:00 level=INFO msg="Getting R version" r=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R
time=2025-05-16T07:32:51.530-05:00 level=DEBUG msg="Running command" cmd=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R args=--version
time=2025-05-16T07:32:51.588-05:00 level=INFO msg="Parsing line for R version" l="R version 4.3.3 (2024-02-29) -- \"Angel Food Cake\""
time=2025-05-16T07:32:51.588-05:00 level=INFO msg="Detected R version" version=4.3.3
time=2025-05-16T07:32:51.588-05:00 level=DEBUG msg="Successful validation for R executable" rExecutable=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R
time=2025-05-16T07:32:51.588-05:00 level=DEBUG msg="Successful validation for Python executable" pythonExecutable="" version=3.12.10
time=2025-05-16T07:32:51.627-05:00 level=DEBUG msg="applying defaults to Config.R section" before="&{Version: PackageFile: PackageManager: RequiresRVersion:}"
time=2025-05-16T07:32:51.627-05:00 level=INFO msg="Getting renv lockfile path from R executable" r=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R
time=2025-05-16T07:32:51.627-05:00 level=DEBUG msg="Running command" cmd=/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R args="-s -e renv::paths$lockfile()"
time=2025-05-16T07:32:52.468-05:00 level=INFO msg="Parsing line for renv::path output" l="[1] \"/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv.lock\""
time=2025-05-16T07:32:52.468-05:00 level=INFO msg="renv::paths$lockfile returned lockfile path" path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv.lock
time=2025-05-16T07:32:52.468-05:00 level=DEBUG msg="renv lockfile found via R executable" renv_lock=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv.lock
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="after applying defaults to Config.R section" after="&{Version:4.3.3 PackageFile:renv.lock PackageManager:renv RequiresRVersion:~=4.3.0}"
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="New account derived state created" account=dogfood config=usage-metrics-dashboard-E27U
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="Looking for R on PATH" local_id=vlQU3DgDfTpWyU31 PATH=/Users/jkeane/.nvm/versions/node/v22.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/quarto/bin
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="Found R executable from PATH" local_id=vlQU3DgDfTpWyU31 path=/usr/local/bin/R
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="Validating path to R executable found" local_id=vlQU3DgDfTpWyU31 path=/usr/local/bin/R
time=2025-05-16T07:32:52.470-05:00 level=INFO msg="Getting R version" local_id=vlQU3DgDfTpWyU31 r=/usr/local/bin/R
time=2025-05-16T07:32:52.470-05:00 level=DEBUG msg="Running command" local_id=vlQU3DgDfTpWyU31 cmd=/usr/local/bin/R args=--version
time=2025-05-16T07:32:52.494-05:00 level=INFO msg="Parsing line for R version" local_id=vlQU3DgDfTpWyU31 l="R version 4.5.0 (2025-04-11) -- \"How About a Twenty-Six\""
time=2025-05-16T07:32:52.494-05:00 level=INFO msg="Detected R version" local_id=vlQU3DgDfTpWyU31 version=4.5.0
time=2025-05-16T07:32:52.494-05:00 level=DEBUG msg="Successful validation for R executable" local_id=vlQU3DgDfTpWyU31 rExecutable=/usr/local/bin/R
time=2025-05-16T07:32:52.494-05:00 level=DEBUG msg="New publisher derived from state" local_id=vlQU3DgDfTpWyU31 account=dogfood config=usage-metrics-dashboard-E27U
time=2025-05-16T07:32:52.494-05:00 level=INFO msg="Access Log" method=POST url="/api/deployments/deployment-CJSO?dir=.&r=%2FLibrary%2FFrameworks%2FR.framework%2FVersions%2F4.3-arm64%2FResources%2Fbin%2FR&python=%2Fopt%2Fhomebrew%2Fbin%2Fpython3.12" elapsed_ms=965 status=202 req_size=91 resp_size=31 client_addr=127.0.0.1:54266 req.account=dogfood req.config=usage-metrics-dashboard-E27U req.secrets=map[] req.insecure=false
time=2025-05-16T07:32:52.494-05:00 level=INFO msg="Publishing from directory" local_id=vlQU3DgDfTpWyU31 event_op=agent path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard localID=vlQU3DgDfTpWyU31
time=2025-05-16T07:32:52.495-05:00 level=INFO msg="Starting deployment to server" local_id=vlQU3DgDfTpWyU31 server=https://dogfood.team.pct.posit.it
time=2025-05-16T07:32:52.495-05:00 level=INFO msg="Updating deployment" local_id=vlQU3DgDfTpWyU31 content_id=ba28e7d7-f283-4bea-bbdb-51f46c82c339
time=2025-05-16T07:32:52.495-05:00 level=DEBUG msg="Built manifest from config" local_id=vlQU3DgDfTpWyU31 config=usage-metrics-dashboard-E27U
time=2025-05-16T07:32:52.495-05:00 level=INFO msg="Collecting R package descriptions" local_id=vlQU3DgDfTpWyU31 event_op=publish/getRPackageDescriptions
time=2025-05-16T07:32:52.495-05:00 level=DEBUG msg="Collecting manifest R packages" local_id=vlQU3DgDfTpWyU31 event_op=publish/getRPackageDescriptions lockfile=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv.lock
time=2025-05-16T07:32:52.496-05:00 level=DEBUG msg="Running command" local_id=vlQU3DgDfTpWyU31 event_op=publish/getRPackageDescriptions cmd=/usr/local/bin/R args="-s -e cat(.libPaths(), sep=\"\\n\")"
time=2025-05-16T07:32:53.001-05:00 level=DEBUG msg="Running command" local_id=vlQU3DgDfTpWyU31 event_op=publish/getRPackageDescriptions cmd=/usr/local/bin/R args="-s -e (function() { pkgs <- available.packages( repos = setNames(c(\"https://cloud.r-project.org\"), c(\"CRAN\")), type = \"source\", filters = c(getOption(\"rsconnect.available_packages_filters\", default = c()), \"duplicates\"));info <- pkgs[,c(\"Package\", \"Version\", \"Repository\")];apply(info, 1, function(x) { cat(x, sep=\" \", collapse=\"\\n\") } );invisible()})()"
time=2025-05-16T07:32:54.027-05:00 level=DEBUG msg="Running command" local_id=vlQU3DgDfTpWyU31 event_op=publish/getRPackageDescriptions cmd=/usr/local/bin/R args="-s -e (function() { if (requireNamespace(\"BiocManager\", quietly = TRUE) || requireNamespace(\"BiocInstaller\", quietly = TRUE)) {repos <- getFromNamespace(\"renv_bioconductor_repos\", \"renv\")(\"/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard\"); repos <- repos[setdiff(names(repos), \"CRAN\")]; cat(repos, labels=names(repos), fill=1); invisible()}})()"

Logs URL:  https://dogfood.team.pct.posit.it/connect/#/apps/ba28e7d7-f283-4bea-bbdb-51f46c82c339/logs
time=2025-05-16T07:32:54.534-05:00 level=DEBUG msg="Attempting to update deployment record" local_id=vlQU3DgDfTpWyU31 path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/.posit/publish/deployments/deployment-CJSO.toml localIdIfDeploying=vlQU3DgDfTpWyU31
time=2025-05-16T07:32:54.537-05:00 level=DEBUG msg="Updating deployment record" local_id=vlQU3DgDfTpWyU31 path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/.posit/publish/deployments/deployment-CJSO.toml
time=2025-05-16T07:32:54.537-05:00 level=ERROR msg="Deployment failed" local_id=vlQU3DgDfTpWyU31 error="package MASS: versions in lockfile '7.3-60.0.1' and library '7.3-65' are out of sync. Use renv::restore() or renv::snapshot() to synchronize"
time=2025-05-16T07:32:54.678-05:00 level=DEBUG msg="Picking directory from request" directory=.
time=2025-05-16T07:32:54.678-05:00 level=DEBUG msg="Picking directory from request" directory=.
time=2025-05-16T07:32:54.687-05:00 level=DEBUG msg="excluding directory" path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv/library
time=2025-05-16T07:32:54.687-05:00 level=DEBUG msg="excluding directory" path=/Users/jkeane/repos/connect-extensions/extensions/usage-metrics-dashboard/renv/staging
time=2025-05-16T07:32:54.688-05:00 level=INFO msg="Access Log" method=GET url="/api/deployments?dir=.&recursive=true" elapsed_ms=9 status=200 req_size=0 resp_size=2034 client_addr=127.0.0.1:54286
time=2025-05-16T07:32:54.986-05:00 level=DEBUG msg="API request" method=GET path=/__api__/v1/content/ba28e7d7-f283-4bea-bbdb-51f46c82c339/environment body="" response=[] error=<nil>
time=2025-05-16T07:32:54.987-05:00 level=INFO msg="Access Log" method=GET url="/api/deployments/deployment-CJSO/environment?dir=." elapsed_ms=308 status=200 req_size=0 resp_size=3 client_addr=127.0.0.1:54285
```

</details>

## Problem Statement

I have a project that I've configured to run in R 4.3.3 in positron (though 4.5.0 is on my path as the default). In some portions of the logs, we detect 4.3.3 correctly, but in others (and critically when we call `renv::status()` and then block deploying if that's not clean), we are detecting 4.5.0 and so getting the library(s) wrong and incorrectly saying that there's a package mismatch.

## Steps to Reproduce

Use an interpreter in Positron that is different from the default path. 

And as a note if anyone else is running into this: I ran `rig default 4.3-arm64` to get make that 4.3.3 executable on my path, and that let the deploy go through just fine.

### PR DESCRIPTION
**Pull request by marcosnav**
## Intent

Fix inconsistent runtime discovery and selection when deploying from Positron.

Fixes #2648 #2663

## Type of Change

- - [x] Bug Fix 
- - [ ] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## Approach

The API deployment handler was taking into account the preferred runtime at the beginning but it was ignoring it after some initial validations.

Updated the necessary methods to make use of the preferred runtime across the complete deployment request.

## User Impact

Users should be able to deploy with the selected runtime in Positron.

## Automated Tests

Updated the related unit tests

## Directions for Reviewers

Try deploying content from Positron, while selecting a different R or Python version and seeing the deployment go through with success.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

**Review by dotNomad — COMMENTED** [review]
Pulled this down and tried this out in Positron using the VSIX from the CI `dist` artifact.

I saw the same issue described. When publishing with a non-default R version installed I see the output:

```
ime=2025-07-17T11:04:10.487-07:00 level=INFO msg="Getting R version" r=/usr/local/bin/R
time=2025-07-17T11:04:10.487-07:00 level=DEBUG msg="Running command" cmd=/usr/local/bin/R args=--version
time=2025-07-17T11:04:10.522-07:00 level=INFO msg="Parsing line for R version" l="R version 4.4.2 (2024-10-31) -- \"Pile of Leaves\""
time=2025-07-17T11:04:10.522-07:00 level=INFO msg="Detected R version" version=4.4.2
ime=2025-07-17T11:04:10.522-07:00 level=DEBUG msg="Successful validation for R executable" rExecutable=/usr/local/bin/R
time=2025-07-17T11:04:10.522-07:00 level=INFO msg="Getting renv lockfile path from R executable" r=/usr/local/bin/R
time=2025-07-17T11:04:10.522-07:00 level=DEBUG msg="Running script" cmd=/usr/local/bin/R args=-s script=renv::paths$lockfile()
time=2025-07-17T11:04:10.529-07:00 level=DEBUG msg="Running command" cmd=/usr/local/bin/R args="-s -f /var/folders/wn/83k9zr2s791brfmfk90c_6vh0000gp/T/3474042576"
time=2025-07-17T11:04:11.179-07:00 level=INFO msg="Parsing line for renv::path output" output="- None of the packages recorded in the lockfile are currently installed."
time=2025-07-17T11:04:11.179-07:00 level=INFO msg="Parsing line for renv::path output" output="- Use `renv::restore()` to restore the project library."
```

and the error notification

Image

I was able to publish just fine using the default R interpreter on PATH, but when using the non-default I had the problems above. Let me describe a bit of how I got there.

I use `rig` to install multiple versions of R.

```
❯ rig list
* name       version    aliases
------------------------------------------
  4.3-arm64  (R 4.3.3)
* 4.4-arm64  (R 4.4.2)  release
```

When using Positron with that `R 4.4.2` install everything works great since that is the R that I'm pointed to on PATH.

When I choose the `4.3.3` interpreter in Positron is when I start to see those errors. `4.3.3` is detected in a ton of spots in the Posit Publisher Deployment output, but as soon as I get to the `renv` checking it wants to use the R on PATH.

Happy to provide more information on how to reproduce this.

**Comment by marcosnav** [comment]
@dotNomad Thank you for trying it out. I pushed a new commit addressing the behavior you are seeing. In more detail, the runtime mismatch was happening in two steps:
1. Deploying an existing deployment, there is a two step runtime check that was inconsistent, this one got fixed when creating the PR.
2. Creating a brand new deployment, inspection returns possible configurations, such inspection was using inconsistent runtime versions, the issue you found and now fixed with the latest commit.

File: internal/services/api/post_inspect.go [hunk 1]
```diff
@@ -59,126 +55,147 @@ func getEntrypointPath(projectDir util.AbsolutePath, w http.ResponseWriter, req
...
+}
 
-		response := []postInspectResponseBody{}
+type postInspectHandler struct {
+	base                util.AbsolutePath
+	log                 logging.Logger
+	initializer         configGetter
+	matchingWalker      func([]string, util.AbsolutePath, logging.Logger) (util.Walker, error)
+	interpretersResolve func(util.AbsolutePath, http.ResponseWriter, *http.Request, logging.Logger) (interpreters.RInterpreter, interpreters.PythonInterpreter, error)
+}
```
Comment (marcosnav) [inline internal/services/api/post_inspect.go:68]: Sorry for the bump on changes, I had to re-wire a bit the inspect endpoint handler in order to be testable. We didn't had tests on this one so I went for it.

Comment (dotNomad) [reply internal/services/api/post_inspect.go:68]: No worries thanks for adding the additional tests!

File: internal/services/api/post_inspect.go [hunk 2]
```diff
@@ -59,126 +55,147 @@ func getEntrypointPath(projectDir util.AbsolutePath, w http.ResponseWriter, req
...
+		return
+	}
 
-				i := initialize.NewDefaultInitialize()
-				configs, err := i.GetPossibleConfigs(path, pythonPath, rPath, entrypointPath, log)
-				if err != nil {
-					return err
-				}
+	// Parse and resolve executable paths for Python and R
+	rInterpreter, pythonInterpreter, err := h.interpretersResolve(projectDir, w, req, h.log)
```
[the remark this answers is not in the document]
Comment (dotNomad) [reply internal/services/api/post_inspect.go:90]: Thank you for highlighting this - it makes it much easier to review

**Review by dotNomad — APPROVED** [review]
Pulled this down and tried this on Positron. I attempted a deploy using the default and non-default R interpreter I have installed using `rig` - worked great. I also changed the interpreter I had selected, updated the `renv.lock` and was able to push an update, again worked perfectly.

Absolutely fantastic work @marcosnav
