### PR TITLE
Messaging details for deployed content that runs with error

### LINKED ISSUE #2206: Content failed to start message could be better
I deployed an app, and because it needed an env var set on Connect, it failed to start. The Publisher bar has this:

image

* The (x) looks like something to click to dismiss the message
* If you get that message, instead of having a button that says "View Content", how about "View Logs" and link directly to the logs in Connect? I clicked the button to go to Connect, then had to remember that logs are behind the notepad-looking icon there.

### PR DESCRIPTION
**Pull request by marcosnav**
## Intent

This PR applies some presentational details for content that for some reason fails to start, this is only for content that has runtime.

- Showing a warning sign now, instead of an "x" icon that mistakenly suggested to be clickable
- The button reads as "View Content Logs" and directs to Connect content logs page.

Screen Shot 2024-10-11 at 14 34 30

Fixes #2206 

## Approach

Just some presentational changes and checks for errored deployments.

## Automated Tests

Added some unit tests around the Agent Errors type guards

## Directions for Reviewers

- [ ] Deploy an R or Python content item that has some code with errors in it - forcing it to fail at runtime. The message should be better now.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

File: extensions/vscode/src/api/types/error.ts [hunk 1]
```diff
@@ -1,12 +1,17 @@
 // Copyright (C) 2023 by Posit Software, PBC.
 
+import { ErrorCode } from "../../utils/errorTypes";
+
 type AgentErrorBase = {
-  code: string;
+  code: ErrorCode;
```
Comment (dotNomad) [inline extensions/vscode/src/api/types/error.ts:6]: Can we move this type under the API module since it is errors that are coming from our API? Feel free to ignore, just a cleanup suggestion.

**Review by dotNomad — APPROVED** [review]
Minor nit about text styling, otherwise looks great 😎 

> deployed content does not seem to be running. See the logs in Connect for details

Some errors we capitalize the beginning, and others we don't. Same goes for the period ending.

I'd push for sentence case and period endings to be consistent.

**Comment by sagerb** [comment]
Sorry that I didn't provide this input sooner but I regret that we've lost the View Content button. That button is still applicable in the case where the content didn't run, in that you can sometimes fine error information displayed when viewing that content.

An alternative, which I'd like to propose, would be to have your error message include an anchor that would link to showing the logs, and we keep the View Content button as it was. This requires some string parsing/replacement, but we do have an example in our implementation for editing a config file. Check out the usage of the `TextStringWithAnchor` component within the `EvenEasierDeploy` component.

File: extensions/vscode/src/api/types/error.ts (hunk 1 above)
Comment (marcosnav) [reply extensions/vscode/src/api/types/error.ts:6]: Agreed 100% with you, there are some more changes to do on error types and at some point we will consolidate these, hopefully in the near term

**Comment by marcosnav** [comment]
@dotNomad Thanks for the punctuation observation. In my last commit, I went ahead and created a small normalization method to prevent this from happening when the message is derived from an `error` instance in the Go code. Since linting rules for go discourage creating errors with sentence case and period endings, this for error chaining practices.

**Comment by dotNomad** [comment]
> Since linting rules for go discourage creating errors with sentence case and period endings, this for error chaining practices.

Fantastic. Thanks for adding that!
