### PR TITLE
Hiding the associate deployment to existing content functionality for Connect Cloud

### LINKED ISSUE #2686: Add Connect Cloud support for the Homeview
### Description

The Homeview needs Connect Cloud support for:
- Credentials
- Secrets
- Linking to deployment logs
- Associating current deployment with different deployment in Connect Cloud (or at least hide this option)

### LINKED ISSUE #2907: Deployment menu option to "Associate with different deployment" throws error
### Publisher Version

publisher-1.18.1-61-g958868e7-darwin-arm64.vsix

### Connect Version

_No response_

### Your OS

_No response_

### IDE

_No response_

### Content Type to Deploy

_No response_

### Problem Statement

There's an option in the deployment 3dot menu:  `Associate with a different deployment on Connect`

After deploying to connect cloud, this throws an error:  `'posit.publisher.homeView.associateDeployment' not found`
Also, we may want to consider updating the verbiage to Connect Cloud (or entirely hiding the option after a cloud deploy)

NOTE:  I tried this with first deploying to a regular connect server, and the error isn't displayed and a new text box asks to put in a new server url.

### Steps to Reproduce

1. Deploy any project to PCC successful
2. Click the Deployment triple dot menu
3. Select `Associate with a different deployment on Connect`
4. Observe error in bottom right

https://github.com/user-attachments/assets/f406a053-d6d7-43c1-a4bf-4ddab67d0452

### Publisher Output and Logs

_No response_

### PR DESCRIPTION
**Pull request by rodriin**
## Intent

Resolves #2686 
Resolves #2907 

The intent here is to hide Connect functionality that won't be supported for Connect Cloud at the moment. Said functionality in this case refers to the "associate deployment to existing content" functionality.

## Type of Change

- - [ ] Bug Fix 
- - [x] New Feature 
- - [ ] Breaking Change 
- - [ ] Documentation 
- - [ ] Refactor 
- - [ ] Tooling 

## Approach

I have conditionally hidden the unsupported functionality for Connect Cloud using the `serverType` to figure out the product type to hide the unsupported functionality for Connect Cloud.

## User Impact

None.

## Automated Tests

E2E tests pass on CI for this branch.

## Directions for Reviewers

- [ ] Verify that "Associate with different deployment" functionality still works as expected for Connect deployments.
- [ ] Verify that "Associate with different deployment" functionality is not available for Connect Cloud deployments.
- [ ] Verify that "Associate with different deployment" functionality shows/hides accordingly when switching between Connect and Connect Cloud deployment configurations in the "..." menu and right below the "Deploy Your Project" button.

## Checklist

- [ ] I have updated [CHANGELOG.md](../CHANGELOG.md) to cover notable changes.

### CODE REVIEW

**Comment by rodriin** [comment]
@dotNomad 

>I'm not able to see the `posit.publisher.homeView.associateDeployment` command in the context menu when I have a Connect deployment selected in Publisher.

Is your deployment deployed? I experienced that when my deployment was brand new and not deployed and I believ that is expected, but it shows once you make your first deployment attempt.

>Additionally I can still access the command through the command palette. It "works" with either type of product deployment selected. When I use it for Connect Cloud deployments it updates the Content GUID in the deployment file.

Very cool, I didn't realize you could do that. Can you show me how to do that please? Also this makes me wonder whether we are actually supporting this feature and I just didn't think were. I guess I need to see that in action.

**Comment by dotNomad** [comment]
> Is your deployment deployed? I experienced that when my deployment was brand new and not deployed and I believ that is expected, but it shows once you make your first deployment attempt.

Ahhh good catch 🤦 
I missed the `posit.publish.selection.isPreContentRecord == 'false'` in the `package.json` too. Re-looking at this PR. I still think the command palette option is an issue, but I can at least verify the context menu functionality.

> Very cool, I didn't realize you could do that. Can you show me how to do that please? Also this makes me wonder whether we are actually supporting this feature and I just didn't think were. I guess I need to see that in action.

You can access the commands we contribute via the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

**Comment by rodriin** [comment]
@dotNomad I just drafted it. I'll ping you when I have something concrete, thank you!

File: extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue [hunk 1]
```diff
@@ -191,7 +191,7 @@
           </div>
         </template>
         <template v-else>
-          <div v-if="isPreContentRecordWithoutID">
+          <div v-if="isPreContentRecordWithoutID && isConnectPreContentRecord">
```
Comment (dotNomad) [inline extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue:194]: Nice addition here! Great catch

**Review by dotNomad — APPROVED** [review]
Fantastic, clean, and it works great locally 🎉
